version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: company-service-server
    ports:
      - "50051:50051"
    env_file:
      - .env
    volumes:
      - ./server:/app
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: company-service-client
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./client:/app

# docker-compose build --no-cache
# docker-compose up --build
# docker-compose up
# docker-compose down